

```{r}
#5.4a
rm(list=ls())
library(LearnBayes)
y = c(15, 11, 14, 17, 5, 11, 10, 4, 8, 
       10, 7, 9, 11, 3, 6, 1, 1, 4)
fun=function(beta, y) {
  beta0=beta[1]
  beta1=beta[2]
  inde =1:18
  val=y * (beta0 + beta1 * inde)-exp(beta0 + beta1 * inde)
  val =sum(val)
  return(val)
}
#b
fit=laplace(fun, c(0, 0), y)
fit$mode
```

```{r}
#c
mycontour(fun, c(2.2, 3.35, -0.2, -0.01), y)
tpar=list(m = fit$mode, var = fit$var, df = 3)
beta = sir(fun, tpar, 1000, y)
points(beta)
```


```{r}
mean(beta[, 2])
var(beta[, 2])
```


```{r}
#5.5a
rm(list=ls())
fun0= function(lambda, data){
  n0 = data[1]
  n1= data[2]
  n2 =data[3]
  n3 =data[4]
  val = -lambda * (n0 + n1 + n2) + 
    (n1 + 2*n2 -1)* log(lambda) + 
    n3 * log(1-exp(-lambda)*(1+lambda+lambda^2/2))
  return(val)
}

```


```{r}
#b
fun= function(theta, data){
  lambda=exp(theta)
  n0 = data[1]
  n1= data[2]
  n2 =data[3]
  n3 =data[4]
  val = -lambda * (n0 + n1 + n2) + 
         (n1 + 2*n2 -1)* log(lambda) + 
         n3 * log(1-exp(-lambda)*(1+lambda+
         lambda^2/2)) + theta
  return(val)
}
data= c(11, 27, 64, 128)
library(LearnBayes)
fit =laplace(fun, 0, data)
fit
```


```{r}
#c
tpar =list(m = fit$mode, var = fit$var, df = 2)
theta =sir(fun, tpar, 1000, data)
lambda = exp(theta)
plot(density(lambda))

```


```{r}
mean(lambda)
sd(lambda)
```

```{r}
data= c(11, 27, 64, 128)
fit =laplace(fun0, 0, data)
fit
```


```{r}
#5.6a
rm(list=ls())
fun <- function(theta, y){
  lambda.A <- exp(theta[1])
  lambda.B <- exp(theta[2])
  sum(log(0.8*dexp(y, 1/lambda.A) + 
          0.2 * dexp(y, 1/lambda.B)))
}
library(LearnBayes)
y <- c(9.3, 4.9, 3.5, 26, 0.6, 1, 3.5, 26.9, 
       2.6, 20.4, 1, 10, 1.7, 11.3, 7.7, 14.1, 
       24.8, 3.8, 8.4, 1.1, 24.5, 90.7, 16.4, 
       30.7, 8.5, 5.9, 14.7, 0.5, 99.5, 35.2)
mycontour(fun, c(1, 4, -2, 8), y)
```


```{r}
#b
laplace(fun, c(3, 0), y)$mode
#c
laplace(fun, c(2,4), y)$mode
```


```{r}
#5.7a
rm(list=ls())
fun = function(theta, y){
  mu = theta[1]
  sigma.y = exp(theta[2])
  sigma.b = exp(theta[3])
  Y = apply(y, 1,  mean)
  n = dim(y)[2]
  S = apply(y, 1, var) * (n-1)
  loglike = sum(dnorm(Y, mu, sqrt(sigma.y^2/n +sigma.b^2), log = T)+
                  dgamma(S, shape = (n-1)/2, rate = 1/(2*sigma.y^2), log = T))
  return(loglike + theta[2] + theta[3])
}
y = c(1545, 1440, 1440, 1520, 1580, 
      1540, 1555, 1490, 1560, 1495, 
      1595, 1550, 1605, 1510, 1560, 
      1445, 1440, 1595, 1465, 1545, 
      1595, 1630, 1515, 1635, 1625, 
      1520, 1455, 1450, 1480, 1445)
y = matrix(y, nrow = 6, ncol = 5, byrow = T)
fit = laplace(fun, c(1500, 3, 3), y)
fit$mode
laplace(fun, c(1500, 1, 1), y)$mode
laplace(fun, c(1500, 10, 10), y)$mode

```


```{r}

#b
qnorm(c(0.05, 0.95), fit$mode[2], fit$var[2, 2]^0.5)
qnorm(c(0.05, 0.95), fit$mode[3], fit$var[3, 3]^0.5)


```


```{r}
#c
exp(qnorm(c(0.05, 0.95), fit$mode[2], fit$var[2, 2]^0.5))
exp(qnorm(c(0.05, 0.95), fit$mode[3], fit$var[3, 3]^0.5))
```
